config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users

  resources :comments

  resources :links do
    member do
      get 'upvotedlink'
      post 'upvoted', :as => :upvoted
      post 'downvoted', :as => :downvoted
    end
    resources :comments
  end

    root 'links#index'

  resources :subreddits, :path => "/r", :only => [:index, :show, :edit, :new, :create] do
    resources :links
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  belongs_to :nested, :polymorphic => true
  has_many :comments, :as => :nested
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :nested_id, :nested_type)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="hidden_comments">
  <div class="comments_wrapper clearfix">
    <div class="pull-left">
      <p class="lead"><%= comment.body %></p>
      <p><small>submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.try(:name) %></small></p>
    </div>

    <div class="btn-group pull-right">
      <% if comment.user == current_user -%>
        <%= link_to 'delete', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
      <% end %>
    </div>
  </div>
    <%= render :partial => "comments/form", :locals => {:nested_object => comment} %>
    <%= render :partial => "comments/comment", :collection => comment.comments %>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Commenting as: <%= @link.user.name  %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.hidden_field :nested_id, :value => nested_object.id %><br>
    <%= f.hidden_field :nested_type, :value => nested_object.class.to_s %>
  </div>
  <div class="actions">
    <%= f.submit "Add Comment", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user.try(:name) %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Nested:</strong>
  <%= @comment.nested_id %>
</p>

<p>
  <strong>Nested type:</strong>
  <%= @comment.nested_type %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', links_path %>