config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users

  resources :comments

  resources :links do
    member do
      get 'upvotedlink'
      post 'upvoted', :as => :upvoted
      post 'downvoted', :as => :downvoted
    end
    resources :comments
  end

    root 'links#index'

  resources :subreddits, :path => "/r", :only => [:index, :show, :edit, :new, :create] do
    resources :links
  end

end

app/models/link.rb
class Link < ActiveRecord::Base

has_many :votes

has_many :downvotes

belongs_to :user

belongs_to :subreddit

 has_many :comments, :as => :nested

# before_save :linkchecking

# def linkchecking
#   link = Link.where(:url => self.url).first
#   if link == true
#     self.votes.create
#   else
#
#   end
# end



end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :authorized_user, only: [:edit, :update, :destroy]
  before_action :user_select, only: [:new, :edit, :update, :create]
  before_action :sub_select, only: [:new, :edit, :update, :create]

  # GET /links
  # GET /links.json
  def index
    if params[:subreddit_id]
      @subreddit = Subreddit.where(:name => params[:subreddit_id]).first
      @links = @subreddit.links.all
    else
      @links = Link.all.sort_by{|link| link.score}.reverse
      # @links = Link.order("links.score DESC")
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @comment = Comment.new
  end

  # GET /links/new
  def new
    @link = current_user.links.build

  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvoted
    @link = Link.find(params[:id])
    @link.votes.create
    @link.score = (@link.votes.count - @link.downvotes.count)
    @link.save
    redirect_to(links_path)
  end

  def downvoted
    @link = Link.find(params[:id])
    @link.downvotes.create
    @link.score = (@link.votes.count - @link.downvotes.count)
    @link.save
    redirect_to(links_path)
  end

  def upvotedlink
    @link = Link.find(params[:id])
    @link.votes.create
    @link.save
    redirect_to (@link.url)
  end

  def authorized_user
    @link = current_user.links.find_by(id: params[:id])
    redirect_to links_path, notice: "Not authorized to edit this link" if @link.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_link
      @link = Link.find(params[:id])
    end

    def sub_select
      @sub_options = Subreddit.all.collect{ |subreddit| [subreddit.name, subreddit.id] }
    end

    def user_select
      @user_options = User.all.collect{ |user| [user.name, user.id] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :summary, :url, :name, :link_id, :vote, :subreddit_id)
    end
end

app/helpers/links_helper.rb
module LinksHelper


def linkhome
  @link.downvote
  redirect_to(links_path)
end



end

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>
      <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="form-group">
    <%= f.label :subreddit_id %><br>
    <%= f.select :subreddit_id, options_for_select(@sub_options, @link.subreddit_id), :prompt => " " %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit Link", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<% @links.each do |link| %>
  <div class="link row clearfix">
    <h2>
      <%= link_to link.title, link %><br>
      <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> ago by <%= link.user.try(:name) %> on r/<%= link_to link.subreddit.name, subreddit_links_path(:subreddit_id => link.subreddit.name) %></small>
    </h2>
    <div class="btn-group">
      <a class="btn btn-info btn-sm" href="<%= link.url %>">Visit Link</a>
      <%= link_to upvoted_link_path(link), method: :post, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
      <% end %>
      <%= link_to downvoted_link_path(link), method: :post, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down">
          <%= pluralize(link.score, "vote") %>
      <% end %>
        <% if link.user == current_user %>
        	<div class="btn-group">
        		<%= link_to 'edit', edit_link_path(link), class: "btn btn-default btn-sm" %>
        		<%= link_to 'delete', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
        	</div>
        <% end %>
    </div>
  </div>
<% end %>

app/views/links/new.html.erb
<h1>Submit a new link</h1>

<%= render 'form' %>

<%= link_to 'back', links_path, class: "btn btn-default" %>

app/views/links/show.html.erb
<div class="page-header">
  <h1><a href="<%= @link.url %>"><%= @link.title %></a><br>
    <p><%= @link.summary %></p>
    <small>Submitted by <%= @link.user.try(:name) %></small></h1>
</div>

<div class="btn-group">
	<%= link_to 'Visit URL', @link.url, class: "btn btn-primary" %>
</div>

<div class="btn-group pull-right">
  <%= link_to upvoted_link_path(@link), method: :post, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-up"></span>
  <% end %>
  <%= link_to downvoted_link_path(@link), method: :post, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-down">
      <%= pluralize(@link.votes.count - @link.downvotes.count, "vote") %>
    <% end %>
</div>

<% if @link.user == current_user -%>
	<div class="btn-group">
		<%= link_to 'edit', edit_link_path(@link), class: "btn btn-default" %>
		<%= link_to 'delete', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<% end %>
  <%= link_to 'back', links_path, class: "btn btn-default" %>
  </div>

<h3 class="comments_title">
  <%= pluralize(@link.comments.count, "Comment") %>
</h3>

<ul class="media-list">
  <li class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <% if current_user %>
        <%= render :partial => 'comments/form', :locals => {:nested_object => @link} %>
        <% end %>
      </h4>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading"><%= render :partial => "comments/comment", :collection => @link.comments %></h4>
        </div>
      </div>
    </li>
  </ul>