config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users

  resources :comments

  resources :links do
    member do
      get 'upvotedlink'
      post 'upvoted', :as => :upvoted
      post 'downvoted', :as => :downvoted
    end
    resources :comments
  end

    root 'links#index'

  resources :subreddits, :path => "/r", :only => [:index, :show, :edit, :new, :create] do
    resources :links
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raditz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
	<header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "Raditz - is over 9000.", links_path %></div>

        <nav class="collapse navbar-collapse navbar-ex1-collapse">
        	<% if user_signed_in? -%>
						<ul class="nav navbar-nav navbar-right">
							<li><%= link_to 'Submit link', new_link_path %></li>
							<li><%= link_to 'Account', edit_user_registration_path %></li>
							<li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
						</ul>
					<% else -%>
						<ul class="nav navbar-nav pull-right">
							<li><%= link_to 'Sign up', new_user_registration_path %></li>
							<li><%= link_to 'Sign in', new_user_session_path %></li>
						</ul>
					<% end -%>
        </nav>
      </div>
    </div>
  </header>

	<div id="main_content" class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

			<div id="content" class="col-md-9 center-block">
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>